<li id="item_<?PHP echo $this->id ?>" class="<?PHP echo $this->unread==1 ? 'unread' : '' ?>">
    <a class="starr-message <?PHP echo $this->starred==1 ? 'active' : '' ?>" title="<?PHP echo $this->translate('starr') ?>"><span><?PHP echo $this->translate('starr') ?></span></a>
    <a class="mark-message <?PHP echo $this->unread==1 ? 'active' : '' ?>"><span><?PHP echo $this->translate('mark as read') ?></span></a>
    <img src="<?PHP echo Zend_Registry::get('config')->favicons->url . $this->icon ?>" alt="<?PHP echo $this->name ?>" title="<?PHP echo $this->name ?>" width="16" height="16" />
    <?PHP $date = new Zend_Date($this->datetime); ?>
    <span title="<?PHP echo $date->toString('d.MM.YYYY HH:mm'); ?>"><?PHP echo $date->toString('HH:mm'); ?></span>
    <h2><?PHP 
        $title = $this->highlite($this->title, Zend_Registry::get('search'));
        echo strlen(trim($title))==0 ? '['.$this->translate('no title').']' : $title;
    ?></h2>
    <a href="<?PHP echo $this->link ?>" class="link">&raquo; <?PHP echo $this->name ?> 
    <?PHP if(Zend_Registry::get('session')->enableRating==1) : ?>
        <span><?PHP echo sprintf("%1.2g",$this->rating); ?></span>
    <?PHP endif; ?>
    </a>
    <div class="content">
        <?PHP echo $this->lazyimg( $this->highlite($this->content, Zend_Registry::get('search')) ); ?>
    </div>
    <span class="date">
    <?PHP echo $date->toString('d.MM.'); ?>
    </span>
</li>