 <div id="settings">
    <h1 class="settings"><?PHP echo $this->translate('settings'); ?></h1>
    <ul id="settings-data">
        <li>
            <label><?PHP echo $this->translate('Delete Entries older than'); ?></label> 
            <input type="text" value="<?PHP echo Zend_Registry::get('session')->deleteItems ?>" id="deleteItems" title="<?PHP echo $this->translate('Entries old than this value will be deleted. Enter 0 for never deleting items.'); ?>" /> <?PHP echo $this->translate('days'); ?>
        </li>
        <li>
            <label><?PHP echo $this->translate('Position of Images'); ?></label>
            <?PHP echo $this->formSelect(
                            'imagesPosition', 
                            Zend_Registry::get('session')->imagesPosition, 
                            null,
                            array(
                                'top'    => $this->translate('top'),
                                'bottom' => $this->translate('bottom')
                            )
                        ); ?>
        </li>
        <li>
            <label><?PHP echo $this->translate('Height of Imagebox'); ?></label>
            <?PHP echo $this->formSelect(
                            'imagesHeight', 
                            Zend_Registry::get('session')->imagesHeight,
                            null,
                            array(
                                '1' => $this->translate('1 row'),
                                '2' => $this->translate('2 rows'),
                                '3' => $this->translate('3 rows')
                            )
                        ); ?>
            </select>
        </li>
        <li>
            <label><?PHP echo $this->translate('Language'); ?></label>
            <?PHP 
                    echo $this->formSelect(
                            'language', 
                            Zend_Registry::get('session')->language,
                            null,
                            $this->languages
                        ); ?>
            </select>
        </li>
        <li>
            <label><?PHP echo $this->translate('Refresh RSS Feeds every'); ?></label> 
            <input type="text" value="<?PHP echo Zend_Registry::get('session')->refresh ?>" id="refresh" /> <?PHP echo $this->translate('minutes'); ?>
        </li>
        <li>
            <label><?PHP echo $this->translate('Items per Page'); ?></label> 
            <input type="text" value="<?PHP echo Zend_Registry::get('session')->itemsperpage ?>" id="itemsperpage" />
        </li>
        <li>
            <label><?PHP echo $this->translate('Save open Categories'); ?></label> 
            <input type="checkbox" value='1' id="saveOpenCategories" <?PHP echo Zend_Registry::get('session')->saveOpenCategories==1 ? 'checked="checked"' : '' ?>/>
        </li>
        <li>
            <label><?PHP echo $this->translate('First show unread Items'); ?></label> 
            <input type="checkbox" value='1' id="firstUnread" <?PHP echo Zend_Registry::get('session')->firstUnread==1 ? 'checked="checked"' : '' ?>/>
        </li>
        <li>
            <label><?PHP echo $this->translate('Open links in new window'); ?></label> 
            <input type="checkbox" value='1' id="newWindow" <?PHP echo Zend_Registry::get('session')->newWindow==1 ? 'checked="checked"' : '' ?>/>
        </li>
        <li>
            <label><?PHP echo $this->translate('Anonymizer URL (e.g. http://anonym.to/?)'); ?></label> 
            <input type="text" value="<?PHP echo Zend_Registry::get('session')->anonymizer ?>" id="anonymizer" />
            
            
            <input type="hidden" value='<?PHP echo Zend_Registry::get('session')->enableRating ?>' id="enableRating" />
        </li>
        <?PHP
        /*
        <li>
            <label><?PHP echo $this->translate('Enable rating'); ?></label> 
            <input type="checkbox" value='1' id="enableRating" <?PHP echo Zend_Registry::get('session')->enableRating==1 ? 'checked="checked"' : '' ?>/>
        </li>
        */
        ?>
        <li>
            <label><?PHP echo $this->translate('Activate login'); ?></label> 
            <input type="checkbox" value="1" id="activate_login" <?PHP echo strlen($this->username)>0 ? 'checked="checked"' : '' ?>/>
        </li>
        <li>
            <label><?PHP echo $this->translate('Username'); ?></label> 
            <input type="text" value="<?PHP echo $this->username ?>" id="username" <?PHP echo strlen($this->username)==0 ? 'disabled="disabled"' : '' ?>/>
        </li>
        <li>
            <label><?PHP echo $this->translate('Password'); ?></label> 
            <input type="password" id="password" <?PHP echo strlen($this->username)==0 ? 'disabled="disabled"' : '' ?>/>
        </li>
        <li>
            <label><?PHP echo $this->translate('again Password'); ?></label> 
            <input type="password" id="password_again" <?PHP echo strlen($this->username)==0 ? 'disabled="disabled"' : '' ?>/>
        </li>
        <li class="bookmark">
            <?PHP echo $this->translate('Drag this link into your bookmarks bar. Everytime you want to subscribe an open feed, click on this bookmark.'); ?>
            <a><?PHP echo $this->translate('subscribe feed'); ?></a>
        </li>
    </ul>
</div>
