<li id="item_<?PHP echo $this->id ?>" class="<?PHP echo $this->unread==1 ? 'unread' : '' ?>">
    <a class="starr-message <?PHP echo $this->starred==1 ? 'active' : '' ?>" title="<?PHP echo $this->translate('starr') ?>"><span><?PHP echo $this->translate('starr') ?></span></a>
    <a class="mark-message <?PHP echo $this->unread==1 ? 'active' : '' ?>" title="<?PHP echo $this->translate('mark as read') ?>"><span><?PHP echo $this->translate('mark as read') ?></span></a>
    <img src="<?PHP echo Zend_Registry::get('config')->favicons->url . $this->icon ?>" alt="<?PHP echo $this->name ?>" title="<?PHP echo $this->name ?>" />
    <?PHP $date = new Zend_Date($this->datetime); ?>
    <span title="<?PHP echo $date->toString('d.MM.YYYY HH:mm'); ?>"><?PHP echo $date->toString('HH:mm'); ?></span>
    <h2><?PHP echo $this->highlite($this->title, Zend_Registry::get('search')) ?></h2>
    <a href="<?PHP echo $this->link ?>">&raquo; <?PHP echo $this->name ?></a>
    <span class="date">
    <?PHP echo $date->toString('d.MM.'); ?>
    </span>
    <div class="content">
        <?PHP echo $this->lazyimg( $this->highlite($this->content, Zend_Registry::get('search')) ); ?>
    </div>
</li>